---
title: Descriptives of Results
output: html_document
---

## Introduction

This is a dynamic Rmd document that will briefly analyse the results from this project.
The main goal was to examine the effect that price of a Private room has on the number of yearly reviews. 
In the graph below, we generated the results of 5 capital cities in western Europe to answer the research question. .

## Image


```{r display_image, out.width = '100%'}
image_path <- '../../gen/analysis/output/bar_chart.png'
image <- readPNG(image_path)
grid.raster(image)
```

## Data Summary

Based on the graph data, we can see that in 3 of the 5 cities that we studied the expensive private rooms tend to have a higher yearly average of reviews. 
In Paris, the difference in yearly reviews between cheaper and more expensive rooms is minimal. However, when it comes to Amsterdam, the more budget-friendly rooms take the lead in terms of yearly average reviews.
In conclusion, the expensive rooms tend to receive more yearly reviews compared to their cheaper counterparts across the cities we have examined.
