ANALYSIS = ../../gen/analysis/output
PAPER = ../../gen/paper/output


all: $(PAPER)/descriptives.Rmd $(PAPER)/descriptives.html

$(PAPER)/descriptives.Rmd $(PAPER)/descriptives.html: script_to_generate_descriptives.R 
	R --vanilla < script_to_generate_descriptives.R 





